import type { IJob } from "@/types/job";

export type AdminJobStatus = "APPROVED" | "PENDING" | "REJECTED" | "EXPIRED";

export interface AdminJob extends IJob {
  status: AdminJobStatus;
  isFeatured: boolean;
  companyName: string;
  companyLogo: string;
}

export const DUMMY_JOBS: AdminJob[] = [
  {
    id: "j1",
    title: "Senior Full Stack Developer",
    description: "Looking for an experienced developer...",
    category: "Software Development",
    tags: ["React", "Node.js", "TypeScript"],
    companyId: "c1",
    companyName: "TechCorp",
    companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=TechCorp",
    status: "APPROVED",
    isFeatured: true,
    jobType: "FULL_TIME",
    salaryMin: 80000,
    salaryMax: 120000,
    createdAt: "2024-03-10T10:00:00Z",
    updatedAt: "2024-03-10T10:00:00Z",
    deadline: "2024-05-10T10:00:00Z",
    views: 100,
  },
  {
    id: "j2",
    title: "Product Designer",
    description: "Creative designer needed for mobile apps...",
    category: "Design",
    tags: ["Figma", "UI/UX"],
    companyId: "c2",
    companyName: "DesignHub",
    companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=DesignHub",
    status: "PENDING",
    isFeatured: false,
    jobType: "FULL_TIME",
    salaryMin: 60000,
    salaryMax: 90000,
    createdAt: "2024-04-12T14:30:00Z",
    updatedAt: "2024-04-12T14:30:00Z",
    deadline: "2024-06-12T14:30:00Z",
    views: 100,
  },
  {
    id: "j3",
    title: "Marketing Manager",
    description: "Lead our marketing team...",
    category: "Marketing",
    tags: ["SEO", "Campaigns"],
    companyId: "c3",
    companyName: "GrowthLabs",
    companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=GrowthLabs",
    status: "APPROVED",
    isFeatured: false,
    jobType: "PART_TIME",
    salaryMin: 40000,
    salaryMax: 55000,
    createdAt: "2024-02-15T09:00:00Z",
    updatedAt: "2024-02-15T09:00:00Z",
    deadline: "2024-04-15T09:00:00Z",
    views: 100,
  },
  {
    id: "j4",
    title: "Data Analyst",
    description: "Analyze large datasets...",
    category: "Data Science",
    tags: ["Python", "SQL"],
    companyId: "c4",
    companyName: "DataFlow",
    companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=DataFlow",
    status: "EXPIRED",
    isFeatured: false,
    jobType: "CONTRACT",
    salaryMin: 50,
    salaryMax: 80,
    createdAt: "2024-01-20T11:00:00Z",
    updatedAt: "2024-01-20T11:00:00Z",
    deadline: "2024-03-20T11:00:00Z",
    views: 100,
  },
  {
    id: "j5",
    title: "Junior Frontend Developer",
    description: "Start your career with us...",
    category: "Software Development",
    tags: ["HTML", "CSS", "JS"],
    companyId: "c5",
    companyName: "StartUp Inc",
    companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=StartUp",
    status: "REJECTED",
    isFeatured: false,
    jobType: "INTERN",
    salaryMin: 20000,
    salaryMax: 30000,
    createdAt: "2024-04-10T16:00:00Z",
    updatedAt: "2024-04-10T16:00:00Z",
    deadline: "2024-05-10T16:00:00Z",
    views: 100,
  },
];
